# Generated by Django 5.0.6 on 2025-07-04 00:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('rut', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('rubro', models.CharField(blank=True, help_text='Rubro o industria de la empresa.', max_length=100, null=True)),
                ('es_ipsa', models.BooleanField(default=False, help_text='Indica si la empresa forma parte del índice IPSA.')),
                ('notificacion_enviada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('organizacion', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateTimeField()),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('url_documento', models.URLField(max_length=500)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='alerts.empresa')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='HechoEsencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('fecha_publicacion', models.DateTimeField()),
                ('resumen', models.TextField(blank=True, help_text='Resumen del hecho esencial generado por IA.', null=True)),
                ('relevancia', models.IntegerField(blank=True, choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], help_text='Nivel de relevancia determinado por IA.', null=True)),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hechos_esenciales', to='alerts.empresa')),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dominio', models.CharField(help_text='Ej: empresa.com', max_length=80)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('suscripcion_activa', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='alerts.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suscripciones', models.ManyToManyField(blank=True, related_name='perfiles_suscritos', to='alerts.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido')], default='pendiente', max_length=30)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='alerts.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('hecho_esencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.hechoesencial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'hecho_esencial')},
            },
        ),
    ]
