# Generated by Django 5.0.6 on 2025-07-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_informeenviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='plan',
            field=models.CharField(choices=[('gratis', 'Gratis'), ('premium', 'Premium')], default='gratis', max_length=20),
        ),
    ]
