# Generated by Django 5.0.6 on 2025-07-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_organizacion_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='hechoesencial',
            name='categoria',
            field=models.CharField(choices=[('CRITICO', 'Crítico'), ('IMPORTANTE', 'Importante'), ('MODERADO', 'Moderado'), ('RUTINARIO', 'Rutinario')], default='MODERADO', help_text='Categoría según criterios profesionales', max_length=20),
        ),
        migrations.AddField(
            model_name='hechoesencial',
            name='es_empresa_ipsa',
            field=models.BooleanField(default=False, help_text='Indica si la empresa es parte del IPSA al momento del hecho'),
        ),
        migrations.AddField(
            model_name='hechoesencial',
            name='materia',
            field=models.CharField(blank=True, help_text='Contexto adicional del hecho', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hechoesencial',
            name='relevancia_profesional',
            field=models.FloatField(default=5.0, help_text='Relevancia profesional (1-10)'),
        ),
        migrations.CreateModel(
            name='DocumentoSII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CIRCULAR', 'Circular'), ('RESOLUCION', 'Resolución'), ('JURISPRUDENCIA', 'Jurisprudencia')], max_length=20)),
                ('numero', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=500)),
                ('fecha_publicacion', models.DateField()),
                ('contenido', models.TextField(blank=True, null=True)),
                ('resumen', models.TextField(blank=True, help_text='Resumen generado por IA', null=True)),
                ('relevancia', models.IntegerField(default=2, help_text='Relevancia (1-3)')),
                ('es_relevante', models.BooleanField(default=True, help_text='Si debe incluirse en informes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
                'unique_together': {('tipo_documento', 'numero')},
            },
        ),
    ]
